services:
  - type: web
    name: laravel-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          type: pserv
          name: mysql
          property: host
      - key: DB_PORT
        fromService:
          type: pserv
          name: mysql
          property: port
      - key: DB_DATABASE
        value: laravel
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        fromService:
          type: pserv
          name: mysql
          property: password

databases:
  - name: mysql
    databaseName: laravel
    user: root
